######################################################
#                  Media Libraries                   #
######################################################
libraries:
  Movies:
    delete_collections:
      configured: true
      managed: true
      less: 1
    collection_files:
      # - repo: movies/awards
      #   asset_directory: config/assets/awards
      # - repo: movies/movies
      #   asset_directory: config/assets/collections
      # - repo: movies/hidden
      #   asset_directory: config/assets/collections
      # - repo: movies/tmdb
      #   asset_directory: config/assets/collections
      - repo: charts
        asset_directory: config/assets/charts
      # - repo: movies/studios
      #   asset_directory: config/assets/studios
      # - repo: movies/people
      #   asset_directory: config/assets/people
      # - repo: movies/trakt
      #   asset_directory: config/assets/collections
      # - repo: streaming
      #   asset_directory: config/assets/streaming
      # - repo: movies/seasonal
      #   asset_directory: config/assets/seasonal
    remove_overlays: true
    overlay_files:
      - reapply_overlays: true
      - repo: overlays/movies
    radarr:
      url: http://arr-suite-radarr:7878
      token: $RADARR_TOKEN
      add_missing: false
      add_existing: false
      upgrade_existing: false
      monitor_existing: false
      root_folder_path: /media/movies
      monitor: true
      availability: released
      quality_profile: 1080p Balanced
      tag:
      search: true
      radarr_path:
      plex_path:
      ignore_cache: false
    operations:
      assets_for_all: true
      split_duplicates: false
      content_rating_mapper:
        gb/12A: gb/12
#   TV Shows:
#     delete_collections:
#       configured: false
#       managed: true
#       less: 1
#     collection_files:
#       - repo: tv/tv
#         asset_directory: config/assets/collections
#       - repo: tv/hidden
#         asset_directory: config/assets/collections
#       - repo: tv/trakt
#         asset_directory: config/assets/collections
#       - repo: charts
#         asset_directory: config/assets/charts
#       - repo: streaming
#         asset_directory: config/assets/streaming
#       - repo: tv/seasonal
#         asset_directory: config/assets/seasonal
#     metadata_files:
#       - repo: tv/metadata
#     remove_overlays: false
#     overlay_files:
#       - reapply_overlays: false
#       - repo: overlays/tv
#     sonarr:
#       url: http://arr-suite-sonarr:8989
#       token: $SONARR_TOKEN
#       cutoff_search: false
#       monitor: all
#       add_missing: false
#       add_existing: false
#       root_folder_path: /media/tv-shows
#       quality_profile: 1080p Balanced
#       language_profile: English
#       upgrade_existing: false
#       monitor_existing: false
#       ignore_cache: false
#       series_type: standard
#       season_folder: true
#       sonarr_path:
#       plex_path:
#     operations:
#       assets_for_all: true
#       split_duplicates: false
#       item_tmdb_season_titles: true
#       content_rating_mapper:
#         gb/12A: gb/12
#       metadata_backup:
#         path: metadata/tv.yml
#         sync_tags: true
#         add_blank_entries: true
# playlist_files:
# - default: playlist                  # This is a file within Kometa's defaults folder
#   template_variables:
#     libraries: Movies, TV Shows      # list of libraries that you want the Kometa Defaults playlists to look at


######################################################
#                      Settings                      #
######################################################
settings:
  cache: true
  cache_expiration: 60
  asset_folders: true
  show_missing_assets: false
  create_asset_folders: true
  sync_mode: sync
  show_unmanaged: true
  show_filtered: true
  show_missing: true
  save_missing: true
  run_again_delay: 2
  missing_only_released: true
  delete_below_minimum: false
  notifiarr_collection_creation: true
  notifiarr_collection_addition: true
  notifiarr_collection_removing: true
  tvdb_language: default
  only_filter_missing: false
  delete_not_scheduled: false
  show_missing_season_assets: false
  ignore_ids:
  ignore_imdb_ids:
  asset_depth: 2
  show_options: false
  dimensional_asset_rename: true
  download_url_assets: true
  minimum_items: 2
  verify_ssl: true
  default_collection_order: release
  item_refresh_delay: 0
  playlist_sync_to_users: all
  custom_repo: https://raw.githubusercontent.com/HoganMcDonald/Kometa-Configs/main/configs/
  show_missing_episode_assets: false
  show_asset_not_needed: false
  prioritize_assets: true
  playlist_report: true
  check_nightly: true
  show_unconfigured: true
  playlist_exclude_users:
  asset_directory:
  run_order:
  - operations
  - metadata
  - collections
  - overlays
  overlay_filetype: png
  overlay_quality:
  overlay_artwork_filetype: png
  overlay_artwork_quality:


######################################################
#                     Services                       #
######################################################
plex:                                # Can be individually specified per library as well; REQUIRED for the script to run
  url: $PLEX_URL
  token: $PLEX_TOKEN
  timeout: 60
  db_cache: 40
  verify_ssl: true
  clean_bundles: true
  empty_trash: true
  optimize: true
tmdb:
  apikey: $TMDB_APIKEY
  cache_expiration: 60
  language: en
  region:
trakt:
  client_id: $TRAKT_CLIENT_ID
  client_secret: $TRAKT_CLIENT_SECRET
  pin: $TRAKT_PIN
  authorization:
    # authorization section is autofilled by the script
    access_token:
    token_type:
    expires_in:
    refresh_token:
    scope:
    created_at:

# webhooks:
#   error: notifiarr
#   collection_removing: notifiarr
#   run_start: notifiarr
#   run_end: notifiarr
#   changes:
#   - notifiarr
#   version:
#   delete: notifiarr
# tautulli:
#   url: http://tautulli:8181/tautulli
#   apikey:
# omdb:
#   apikey:
#   cache_expiration: 60
# mdblist:
#   apikey:
#   cache_expiration: 60
# notifiarr:
#   apikey:
