######################################################
#                  Media Libraries                   #
######################################################
libraries:
  Movies:
    collection_files:
      # awards
      - default: oscars
        schedule: weekly(monday)

      # collections
      - default: franchise
        schedule: hourly(05)
      - default: studio
        schedule: hourly(05)
      - default: streaming
        schedule: hourly(05)
      - default: seasonal
        schedule: weekly(monday)

      # custom
      - repo: charts
        asset_directory: config/assets/charts
      - repo: movies/people
        asset_directory: config/assets/people
        schedule: hourly(05)
      - repo: movies/trakt
        asset_directory: config/assets/collections
    schedule_overlays: hourly(05)
    remove_overlays: false
    overlay_files:
      - default: resolution
    radarr:
      url: http://arr-suite-radarr:7878
      token: $RADARR_TOKEN
      add_missing: false
      add_existing: false
      upgrade_existing: false
      monitor_existing: false
      root_folder_path: /media/movies
      monitor: true
      availability: released
      quality_profile: 1080p Balanced
      tag:
      search: true
      radarr_path:
      plex_path:
      ignore_cache: false
    operations:
      assets_for_all: true
      split_duplicates: false
      delete_collections:
        configured: false
        managed: false
  TV Shows:
    collection_files:
      # collections
      - default: streaming
        schedule: hourly(05)

      # custom
      - repo: charts
        asset_directory: config/assets/charts
      - repo: tv/trakt
        asset_directory: config/assets/collections
    metadata_files:
      - repo: tv/metadata
    schedule_overlays: hourly(05)
    remove_overlays: false
    overlay_files:
      - default: resolution
    sonarr:
      url: http://arr-suite-sonarr:8989
      token: $SONARR_TOKEN
      add_missing: false
      add_existing: false
      upgrade_existing: false
      monitor_existing: false
      search: true
      monitor: latest
      cutoff_search: false
      root_folder_path: /media/tv-shows
      quality_profile: 1080p Balanced
      language_profile: English
      ignore_cache: false
      series_type: standard
      season_folder: true
      sonarr_path:
      plex_path:
    operations:
      assets_for_all: true
      split_duplicates: false
      item_tmdb_season_titles: true
      delete_collections:
        configured: false
        managed: false
playlist_files:
- default: playlist
  schedule: hourly(05)
  template_variables:
    libraries: Movies, TV Shows


######################################################
#                      Settings                      #
######################################################
settings:
  cache: true
  cache_expiration: 60
  asset_folders: true
  show_missing_assets: false
  create_asset_folders: true
  sync_mode: sync
  show_unmanaged: true
  show_filtered: true
  show_missing: true
  save_missing: true
  run_again_delay: 2
  missing_only_released: true
  delete_below_minimum: false
  notifiarr_collection_creation: true
  notifiarr_collection_addition: true
  notifiarr_collection_removing: true
  tvdb_language: default
  only_filter_missing: false
  delete_not_scheduled: false
  show_missing_season_assets: false
  ignore_ids:
  ignore_imdb_ids:
  asset_depth: 2
  show_options: false
  dimensional_asset_rename: true
  download_url_assets: true
  minimum_items: 2
  verify_ssl: true
  default_collection_order: release
  item_refresh_delay: 0
  playlist_sync_to_users: all
  custom_repo: https://raw.githubusercontent.com/HoganMcDonald/Kometa-Configs/main/configs/
  show_missing_episode_assets: false
  show_asset_not_needed: false
  prioritize_assets: true
  playlist_report: true
  check_nightly: true
  show_unconfigured: true
  playlist_exclude_users:
  asset_directory:
  run_order:
  - operations
  - metadata
  - collections
  - overlays
  overlay_filetype: png
  overlay_quality:
  overlay_artwork_filetype: png
  overlay_artwork_quality:


######################################################
#                     Services                       #
######################################################
plex:                                # Can be individually specified per library as well; REQUIRED for the script to run
  url: $PLEX_URL
  token: $PLEX_TOKEN
  timeout: 60
  db_cache: 40
  verify_ssl: true
  clean_bundles: true
  empty_trash: true
  optimize: true
tmdb:
  apikey: $TMDB_APIKEY
  cache_expiration: 60
  language: en
  region:
trakt:
  client_id: $TRAKT_CLIENT_ID
  client_secret: $TRAKT_CLIENT_SECRET
  pin: $TRAKT_PIN
  authorization:
    # authorization section is autofilled by the script
    access_token:
    token_type:
    expires_in:
    refresh_token:
    scope:
    created_at:

# webhooks:
#   error: notifiarr
#   collection_removing: notifiarr
#   run_start: notifiarr
#   run_end: notifiarr
#   changes:
#   - notifiarr
#   version:
#   delete: notifiarr
# tautulli:
#   url: http://tautulli:8181/tautulli
#   apikey:
# omdb:
#   apikey:
#   cache_expiration: 60
# mdblist:
#   apikey:
#   cache_expiration: 60
# notifiarr:
#   apikey:
