######################################################
#              Trakt Dynamic Collections             #
######################################################

templates:
  trakt:
    trakt_list_details: <<trakt_user_lists>>

dynamic_collections:
  #Create collections based on the Trakt lists associated with the authenticated user.
  Trakt List Collections:
    template: trakt
    type: trakt_user_lists
    data: me
    template_variables:
      sonarr_add_missing: true
      sonarr_search: true
      sonarr_monitor: true
      visible_home: true
      visible_library: false
