######################################################
#              Trakt Dynamic Collections             #
######################################################

templates:
  trakt:
    trakt_list_details: <<trakt_user_lists>>

dynamic_collections:
  #Create collections based on the Trakt lists associated with the authenticated user.
  Trakt List Collections:
    template: trakt
    type: trakt_user_lists
    data: me
    collection_order: custom
    radarr_add_missing: true
    radarr_search: true
    radarr_monitor: true
    visible_home: true
    visible_library: false
