######################################################
#              Trakt Dynamic Collections             #
######################################################

collections:
  Bweep:
    trakt_list:
      - https://trakt.tv/users/hogan12907/lists/bweeps-up-next
    sync_mode: sync
    collection_mode: hide
    schedule: hourly(00-23)
    radarr_add_missing: true
    radarr_search: true
    radarr_monitor: true
    visible_home: false
    visible_library: false
